# Generated by Django 3.2.15 on 2022-08-25 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='pay_plan',
        ),
        migrations.DeleteModel(
            name='PayPlan',
        ),
    ]
